### Inflammatory Bowel Disease (IBD) Clinical Data Analysis

##### Predicting IBD-UC Factors: Correlating Demographics, Disease Phenotype, and Treatment Response
##### Predicting IBD-UC Factors: Exploring the Correlation Between Demographics, Disease Phenotype, and Treatment Response in Inflammatory Bowel Disease

Inflammatory Bowel Disease (IBD) refers to a group of chronic disorders that cause inflammation in the gastrointestinal tract, including Ulcerative Colitis (UC), Crohn's Disease (CD), and Unclassified types. Timely identification and precise prediction of the disease phenotype are essential for effective treatment and enhanced patient outcomes. By analyzing the data, our goal is to identify patterns that may help ***predict*** which patients are at greater risk for severe **UC** forms, allowing for the development of personalized treatment plans.

#### Data Table for the study:  
The Study collects patiest data on Demographics, Disease Phenotype, Treatment and Medication History, Clinical History and Co-morbidities.  
 

| **Variable Name**                    | **Type**          | **Description**                                                                                                                                                     |
|--------------------------------------|-------------------|---------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| **id**                               | Categorical       | Unique identifier for each patient.                                                                                                                                  |
| **Country**                          | Categorical       | The country where the patient resides.                                                                                                                                 |
| **Age**                              | Continuous        | The age of the patient at the time of diagnosis or data collection.                                                                                                  |
| **Sex**                              | Categorical       | The sex of the patient (Male/Female).                                                                                                                                  |
| **Current Smoker**                   | Categorical       | Whether the patient is currently smoking (Yes/No).                                                                                                                   |
| **Year of Dx**                       | Continuous        | The year the patient was diagnosed with IBD.                                                                                                                          |
| **Duration**                         | Continuous        | The duration (in years or months) since the patient was diagnosed with IBD.                                                                                          |
| **UC (E1-E3)**                       | Categorical       | Classification of **Ulcerative Colitis** severity and extent (E1: Rectum only, E2: Left side, E3: Extensive disease).                                                |
| **CD (L1-L4)**                       | Categorical       | **Crohn's Disease** location classification (L1: Ileal, L2: Colonic, L3: Ileocolonic, L4: Upper GI).                                                                  |
| **CD (B1-B3)**                       | Categorical       | **Crohn's Disease** behavior classification (B1: Non-stricturing, Non-penetrating; B2: Stricturing; B3: Penetrating).                                                 |
| **CD (Perianal)**                    | Categorical       | Whether the patient has perianal disease (Yes/No), applicable for **Crohn's Disease**.                                                                              |
| **IBD-U**                            | Categorical       | Whether the patient has **IBD-Unclassified** (Yes/No).                                                                                                              |
| **Previous Surgery**                 | Categorical       | Whether the patient has undergone previous surgical procedures related to IBD (Yes/No).                                                                             |
| **5-ASA**                            | Categorical       | Whether the patient is taking **5-aminosalicylic acid** (5-ASA) as part of treatment (Yes/No).                                                                       |
| **Azathioprine or 6-MP**             | Categorical       | Whether the patient is using **Azathioprine** or **6-mercaptopurine** (Yes/No).                                                                                      |
| **Methotrexate**                     | Categorical       | Whether the patient is using **Methotrexate** for treatment (Yes/No).                                                                                                |
| **Cyclosporine**                     | Categorical       | Whether the patient is using **Cyclosporine** (Yes/No).                                                                                                             |
| **Infliximab**                       | Categorical       | Whether the patient has used **Infliximab**, a biologic treatment for IBD (Yes/No).                                                                                 |
| **Certolizumab**                     | Categorical       | Whether the patient has used **Certolizumab** (Yes/No).                                                                                                            |
| **Golimumab**                        | Categorical       | Whether the patient has used **Golimumab** (Yes/No).                                                                                                               |
| **Adalimumab**                       | Categorical       | Whether the patient has used **Adalimumab** (Yes/No).                                                                                                              |
| **Vedolizumab**                      | Categorical       | Whether the patient has used **Vedolizumab** (Yes/No).                                                                                                             |
| **Current Steroid Use**              | Categorical       | Whether the patient is currently using **steroids** for IBD management (Yes/No).                                                                                     |
| **Tofacitinib**                      | Categorical       | Whether the patient is using **Tofacitinib** (Yes/No).                                                                                                              |
| **Ustekinumab**                      | Categorical       | Whether the patient is using **Ustekinumab** (Yes/No).                                                                                                             |
| **# of Previous Biologics Used**     | Continuous        | The total number of biologic therapies the patient has used in the past.                                                                                           |
| **EIM**                              | Categorical       | Presence of **Extra-intestinal Manifestations (EIM)** (e.g., arthritis, skin lesions, eye inflammation) (Yes/No).                                                   |
| **Other Autoimmune Diseases**        | Categorical       | Whether the patient has other autoimmune diseases (Yes/No).                                                                                                         |
| **Co-morbidities**                   | Categorical       | Whether the patient has additional co-morbidities that may influence disease progression or treatment response (Yes/No).                                             |

### 1.1 Import the data

In [105]:
import pandas as pd 
import numpy as np

# To change scientific numbers to float
np.set_printoptions(formatter={'float_kind':'{:f}'.format})

# load the data
df = pd.read_csv('IBD.csv')

# Set 'id' column as the index
df.set_index('id', inplace=True)

# print the dataframe
df

,Country,Age,Sex,Current Smoker,Year of Dx,Duration,UC (E1-E3),CD(L1-L4),CD (B1-B3),CD (Perianal),...,Golimumab,Adalimumab,vedolizumab,current steroid use,Tofacitinib,Ustekinumab,No.of previous biologic used,EIM,Other autoimmune diseases,Co-morbidities
id,,,,,,,,,,,,,,,,,,,,,
1,Spain,14.0,M,0,2022,2.0,0,L3+L4,B1,0,...,NaN,No,No,Yes,No,No,2,Yes,0,P
2,Spain,55.0,F,0,2023,1.0,0,L1+L4,B1,0,...,NaN,No,No,NaN,No,No,0,NaN,0,0
3,Spain,23.0,F,0,2021,3.0,E3,0,0,0,...,NaN,No,No,NaN,No,No,0,NaN,0,0
4,Spain,23.0,F,0,2018,6.0,E3,0,0,0,...,NaN,No,No,Yes,No,Yes,4,NaN,0,0
5,Spain,9.0,M,0,2018,6.0,E2,0,0,0,...,NaN,No,Yes,Yes,No,No,2,NaN,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5536,France,NaN,F,0,2007,16.0,0,L1,B1,0,...,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,0,0
5537,France,NaN,F,0,2013,10.0,0,L1,B3,1,...,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,0,0
5538,France,NaN,M,0,2019,4.0,0,L1,B1,0,...,NaN,NaN,NaN,NaN,NaN,Yes,1,NaN,0,0
5539,France,NaN,M,0,2021,2.0,0,L1,B1,0,...,NaN,NaN,NaN,Yes,NaN,NaN,0,NaN,0,0
5540,France,NaN,M,0,2003,20.0,0,L3,B1,0,...,NaN,NaN,NaN,NaN,NaN,NaN,0,Yes,0,0

Our data is messesy and have a lot of 'NAN'. Let's explore more.

### 1.2 Check the data

In [106]:
# Top 5 rows
df.head()

,Country,Age,Sex,Current Smoker,Year of Dx,Duration,UC (E1-E3),CD(L1-L4),CD (B1-B3),CD (Perianal),...,Golimumab,Adalimumab,vedolizumab,current steroid use,Tofacitinib,Ustekinumab,No.of previous biologic used,EIM,Other autoimmune diseases,Co-morbidities
id,,,,,,,,,,,,,,,,,,,,,
1,Spain,14.0,M,0,2022,2.0,0,L3+L4,B1,0,...,NaN,No,No,Yes,No,No,2,Yes,0,P
2,Spain,55.0,F,0,2023,1.0,0,L1+L4,B1,0,...,NaN,No,No,NaN,No,No,0,NaN,0,0
3,Spain,23.0,F,0,2021,3.0,E3,0,0,0,...,NaN,No,No,NaN,No,No,0,NaN,0,0
4,Spain,23.0,F,0,2018,6.0,E3,0,0,0,...,NaN,No,No,Yes,No,Yes,4,NaN,0,0
5,Spain,9.0,M,0,2018,6.0,E2,0,0,0,...,NaN,No,Yes,Yes,No,No,2,NaN,0,0

In [107]:
# Bottom 5 rows
df.tail()

,Country,Age,Sex,Current Smoker,Year of Dx,Duration,UC (E1-E3),CD(L1-L4),CD (B1-B3),CD (Perianal),...,Golimumab,Adalimumab,vedolizumab,current steroid use,Tofacitinib,Ustekinumab,No.of previous biologic used,EIM,Other autoimmune diseases,Co-morbidities
id,,,,,,,,,,,,,,,,,,,,,
5536,France,NaN,F,0,2007,16.0,0,L1,B1,0,...,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,0,0
5537,France,NaN,F,0,2013,10.0,0,L1,B3,1,...,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,0,0
5538,France,NaN,M,0,2019,4.0,0,L1,B1,0,...,NaN,NaN,NaN,NaN,NaN,Yes,1,NaN,0,0
5539,France,NaN,M,0,2021,2.0,0,L1,B1,0,...,NaN,NaN,NaN,Yes,NaN,NaN,0,NaN,0,0
5540,France,NaN,M,0,2003,20.0,0,L3,B1,0,...,NaN,NaN,NaN,NaN,NaN,NaN,0,Yes,0,0

In [108]:
# Shape of date
print(f'The IBD data consists of {df.shape[0]} rows and {df.shape[1]} columns.')

The IBD data consists of 5540 rows and 28 columns.

### 1.3 Data Preprocessing

In [109]:
# Check Info of df
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5540 entries, 1 to 5540
Data columns (total 28 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Country                       5540 non-null   object
 1   Age                           4928 non-null   float64
 2   Sex                           5540 non-null   object
 3   Current Smoker                5540 non-null   int64
 4   Year of Dx                    5540 non-null   int64
 5   Duration                      5531 non-null   float64
 6   UC (E1-E3)                    5540 non-null   object
 7   CD(L1-L4)                     5540 non-null   object
 8   CD (B1-B3)                    5540 non-null   object
 9   CD (Perianal)                 5540 non-null   int64
 10  IBD-U                         5540 non-null   int64
 11  Previous surgery              5540 non-null   object
 12  5-ASA                         4460 non-null   object
 13  Azathioprine or 6-MP          4468 non-null   object
 14  Methotrexate                  2655 non-null   object
 15  Cyclosporine                  2686 non-null   object
 16  Infliximab                    4798 non-null   object
 17  Certolizumab                  2724 non-null   object
 18  Golimumab                     2726 non-null   object
 19  Adalimumab                    4782 non-null   object
 20  vedolizumab                   4679 non-null   object
 21  current steroid use           3937 non-null   object
 22  Tofacitinib                   4675 non-null   object
 23  Ustekinumab                   5179 non-null   object
 24  No.of previous biologic used  5540 non-null   object
 25  EIM                           1480 non-null   object
 26  Other autoimmune diseases     5540 non-null   object
 27  Co-morbidities                5540 non-null   object
dtypes: float64(2), int64(4), object(22)
memory usage: 1.2+ MB

From data we need to tackle data types of varibale like Year of Dx, Duration, Adalimumab, current steroid use, No.of previous biologic used,  EIM,   Other autoimmune diseases and Co-morbiditiees.

In [110]:
df['CD (Perianal)'] = df['CD (Perianal)'].fillna('0').astype(str)
df['IBD-U'] = df['IBD-U'].fillna('0').astype(str)
df['Current Smoker'] = df['Current Smoker'].astype(str)
# Convert 'Year of Dx' to datetime format
df['Year of Dx'] = pd.to_datetime(df['Year of Dx'], format='%Y')

Here we convert the variables into string type.

In [111]:
# Check Info of df
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5540 entries, 1 to 5540
Data columns (total 28 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Country                       5540 non-null   object
 1   Age                           4928 non-null   float64
 2   Sex                           5540 non-null   object
 3   Current Smoker                5540 non-null   object
 4   Year of Dx                    5540 non-null   datetime64[ns]
 5   Duration                      5531 non-null   float64
 6   UC (E1-E3)                    5540 non-null   object
 7   CD(L1-L4)                     5540 non-null   object
 8   CD (B1-B3)                    5540 non-null   object
 9   CD (Perianal)                 5540 non-null   object
 10  IBD-U                         5540 non-null   object
 11  Previous surgery              5540 non-null   object
 12  5-ASA                         4460 non-null   object
 13  Azathioprine or 6-MP          4468 non-null   object
 14  Methotrexate                  2655 non-null   object
 15  Cyclosporine                  2686 non-null   object
 16  Infliximab                    4798 non-null   object
 17  Certolizumab                  2724 non-null   object
 18  Golimumab                     2726 non-null   object
 19  Adalimumab                    4782 non-null   object
 20  vedolizumab                   4679 non-null   object
 21  current steroid use           3937 non-null   object
 22  Tofacitinib                   4675 non-null   object
 23  Ustekinumab                   5179 non-null   object
 24  No.of previous biologic used  5540 non-null   object
 25  EIM                           1480 non-null   object
 26  Other autoimmune diseases     5540 non-null   object
 27  Co-morbidities                5540 non-null   object
dtypes: datetime64[ns](1), float64(2), object(25)
memory usage: 1.2+ MB

In [112]:
# Check Missing 
df.isnull().sum()

Country                            0
Age                              612
Sex                                0
Current Smoker                     0
Year of Dx                         0
Duration                           9
UC (E1-E3)                         0
CD(L1-L4)                          0
CD (B1-B3)                         0
CD (Perianal)                      0
IBD-U                              0
Previous surgery                   0
5-ASA                           1080
Azathioprine or 6-MP            1072
Methotrexate                    2885
Cyclosporine                    2854
Infliximab                       742
Certolizumab                    2816
Golimumab                       2814
Adalimumab                       758
vedolizumab                      861
current steroid use             1603
Tofacitinib                      865
Ustekinumab                      361
No.of previous biologic used       0
EIM                             4060
Other autoimmune diseases          0
Co-morbidities                     0
dtype: int64

We have a lot of missing in dataset let's try to mitigate the missing values.

In [113]:
# Step 1: Define the columns for Yes/No mapping
cat_cols_y_n = ['5-ASA', 'Azathioprine or 6-MP', 'Methotrexate', 'Cyclosporine', 
                'Infliximab', 'Certolizumab', 'Golimumab', 'Adalimumab', 
                'vedolizumab', 'current steroid use', 'Tofacitinib', 'Ustekinumab']

# Step 2: Apply the mapping (Yes -> 1, No -> 0) and fill NaN with 0
df[cat_cols_y_n] = df[cat_cols_y_n].apply(lambda col: col.map({'Yes': 1, 'No': 0}).fillna(0))

# Step 3: Verify the changes
print(df[cat_cols_y_n].head())

# Copy the transformed DataFrame
new_df = df.copy()  # or do other transformations if needed

new_df.info()

    5-ASA  Azathioprine or 6-MP  Methotrexate  Cyclosporine  Infliximab  \
id
1     0.0                   0.0           0.0           0.0         1.0
2     0.0                   0.0           0.0           0.0         0.0
3     0.0                   0.0           0.0           0.0         0.0
4     1.0                   0.0           0.0           0.0         0.0
5     1.0                   1.0           0.0           0.0         0.0

    Certolizumab  Golimumab  Adalimumab  vedolizumab  current steroid use  \
id
1            0.0        0.0         0.0          0.0                  1.0
2            0.0        0.0         0.0          0.0                  0.0
3            0.0        0.0         0.0          0.0                  0.0
4            0.0        0.0         0.0          0.0                  1.0
5            0.0        0.0         0.0          1.0                  1.0

    Tofacitinib  Ustekinumab
id
1           0.0          0.0
2           0.0          0.0
3           0.0          0.0
4           0.0          1.0
5           0.0          0.0
<class 'pandas.core.frame.DataFrame'>
Index: 5540 entries, 1 to 5540
Data columns (total 28 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Country                       5540 non-null   object
 1   Age                           4928 non-null   float64
 2   Sex                           5540 non-null   object
 3   Current Smoker                5540 non-null   object
 4   Year of Dx                    5540 non-null   datetime64[ns]
 5   Duration                      5531 non-null   float64
 6   UC (E1-E3)                    5540 non-null   object
 7   CD(L1-L4)                     5540 non-null   object
 8   CD (B1-B3)                    5540 non-null   object
 9   CD (Perianal)                 5540 non-null   object
 10  IBD-U                         5540 non-null   object
 11  Previous surgery              5540 non-null   object
 12  5-ASA                         5540 non-null   float64
 13  Azathioprine or 6-MP          5540 non-null   float64
 14  Methotrexate                  5540 non-null   float64
 15  Cyclosporine                  5540 non-null   float64
 16  Infliximab                    5540 non-null   float64
 17  Certolizumab                  5540 non-null   float64
 18  Golimumab                     5540 non-null   float64
 19  Adalimumab                    5540 non-null   float64
 20  vedolizumab                   5540 non-null   float64
 21  current steroid use           5540 non-null   float64
 22  Tofacitinib                   5540 non-null   float64
 23  Ustekinumab                   5540 non-null   float64
 24  No.of previous biologic used  5540 non-null   object
 25  EIM                           1480 non-null   object
 26  Other autoimmune diseases     5540 non-null   object
 27  Co-morbidities                5540 non-null   object
dtypes: datetime64[ns](1), float64(14), object(13)
memory usage: 1.2+ MB

Coverting the above variables into '0' and '1' for easy of anaysis.

In [114]:
# Concatenate the modified columns to the original DataFrame
# df = pd.concat([df, df[cat_cols_y_n]], axis=1)

# Verify the changes
# print(df.head())

In [115]:
new_df.columns

Index(['Country', 'Age ', 'Sex', 'Current Smoker', 'Year of Dx', 'Duration',
       'UC (E1-E3)', 'CD(L1-L4)', 'CD (B1-B3)', 'CD (Perianal)', 'IBD-U',
       'Previous surgery', '5-ASA', 'Azathioprine or 6-MP', 'Methotrexate',
       'Cyclosporine', 'Infliximab', 'Certolizumab', 'Golimumab', 'Adalimumab',
       'vedolizumab', 'current steroid use', 'Tofacitinib', 'Ustekinumab',
       'No.of previous biologic used', 'EIM', 'Other autoimmune diseases',
       'Co-morbidities'],
      dtype='object')

In [116]:
new_df

,Country,Age,Sex,Current Smoker,Year of Dx,Duration,UC (E1-E3),CD(L1-L4),CD (B1-B3),CD (Perianal),...,Golimumab,Adalimumab,vedolizumab,current steroid use,Tofacitinib,Ustekinumab,No.of previous biologic used,EIM,Other autoimmune diseases,Co-morbidities
id,,,,,,,,,,,,,,,,,,,,,
1,Spain,14.0,M,0,2022-01-01,2.0,0,L3+L4,B1,0,...,0.0,0.0,0.0,1.0,0.0,0.0,2,Yes,0,P
2,Spain,55.0,F,0,2023-01-01,1.0,0,L1+L4,B1,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0,NaN,0,0
3,Spain,23.0,F,0,2021-01-01,3.0,E3,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0,NaN,0,0
4,Spain,23.0,F,0,2018-01-01,6.0,E3,0,0,0,...,0.0,0.0,0.0,1.0,0.0,1.0,4,NaN,0,0
5,Spain,9.0,M,0,2018-01-01,6.0,E2,0,0,0,...,0.0,0.0,1.0,1.0,0.0,0.0,2,NaN,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5536,France,NaN,F,0,2007-01-01,16.0,0,L1,B1,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0,NaN,0,0
5537,France,NaN,F,0,2013-01-01,10.0,0,L1,B3,1,...,0.0,0.0,0.0,0.0,0.0,0.0,0,NaN,0,0
5538,France,NaN,M,0,2019-01-01,4.0,0,L1,B1,0,...,0.0,0.0,0.0,0.0,0.0,1.0,1,NaN,0,0
5539,France,NaN,M,0,2021-01-01,2.0,0,L1,B1,0,...,0.0,0.0,0.0,1.0,0.0,0.0,0,NaN,0,0
5540,France,NaN,M,0,2003-01-01,20.0,0,L3,B1,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0,Yes,0,0

In [117]:
# # Investigate all the elements whithin each Feature 

# for col in df:
#     unique_vals = np.unique(df[col])
#     nr_vals = len(unique_vals)
#     if nr_vals <= 10:
#         print(f"The number of values for feature {col} : {nr_vals} -- {unique_vals}")
#     else:
#         print(f"The number of values for feature {col} : {nr_vals}")

In [118]:
df.columns

Index(['Country', 'Age ', 'Sex', 'Current Smoker', 'Year of Dx', 'Duration',
       'UC (E1-E3)', 'CD(L1-L4)', 'CD (B1-B3)', 'CD (Perianal)', 'IBD-U',
       'Previous surgery', '5-ASA', 'Azathioprine or 6-MP', 'Methotrexate',
       'Cyclosporine', 'Infliximab', 'Certolizumab', 'Golimumab', 'Adalimumab',
       'vedolizumab', 'current steroid use', 'Tofacitinib', 'Ustekinumab',
       'No.of previous biologic used', 'EIM', 'Other autoimmune diseases',
       'Co-morbidities'],
      dtype='object')

In [119]:
# cat_cols_y_n =df[['5-ASA', 'Azathioprine or 6-MP', 'Methotrexate',
#        'Cyclosporine', 'Infliximab', 'Certolizumab', 'Golimumab', 'Adalimumab',
#        'vedolizumab', 'current steroid use', 'Tofacitinib', 'Ustekinumab']]

# for col in cat_cols_y_n:
#     df[col] = df[col].map({'Yes': 1, 'No': 0}).fillna(0)  # Map 'Yes' to 1, 'No' to 0, and fill NaN values with 0

# # Display the DataFrame after applying the mapping
# for col in cat_cols_y_n:
#     print(cat_cols_y_n[col].value_counts())
#     print()

In [120]:
# cat = df[['Sex', 'Current Smoker', 'Previous surgery', 'No.of previous biologic used', 'EIM', 'Other autoimmune diseases',
#        'Co-morbidities']]
# df['Sex'] = df['Sex'].fillna('0').astype(str)
# df['Current Smoker'] = df['Current Smoker'].fillna('0').astype(str)
# df['Previous surgery'] = df['Previous surgery'].fillna('0').astype(str)
# df['No.of previous biologic used'] = df['No.of previous biologic used'].fillna('0').astype(str)
# df['EIM'] = df['EIM'].fillna('0').astype(str)
# df['Other autoimmune diseases'] = df['Other autoimmune diseases'].fillna('0').astype(str)
# df['Co-morbidities'] = df['Co-morbidities'].fillna('0').astype(str)

In [121]:
# new_df.info()

for col in new_df:
    print(new_df[col].value_counts())
    print()

Country
United Kingdom    1802
France            1338
Spain             1017
Italy              768
Poland             377
Greece             238
Name: count, dtype: int64

Age
27.0    171
32.0    169
33.0    167
28.0    158
37.0    154
       ...
87.0      2
83.0      2
91.0      1
82.0      1
84.0      1
Name: count, Length: 81, dtype: int64

Sex
M     2874
F     2662
m        2
f        1
M        1
Name: count, dtype: int64

Current Smoker
0    4972
1     481
3      87
Name: count, dtype: int64

Year of Dx
2019-01-01    445
2018-01-01    442
2017-01-01    375
2020-01-01    353
2015-01-01    347
2016-01-01    326
2021-01-01    308
2014-01-01    278
2022-01-01    277
2013-01-01    272
2012-01-01    263
2011-01-01    240
2010-01-01    232
2023-01-01    171
2008-01-01    168
2009-01-01    167
2007-01-01    136
2006-01-01    113
2005-01-01    105
2004-01-01     89
2003-01-01     64
2000-01-01     62
2002-01-01     47
2001-01-01     42
1998-01-01     37
1999-01-01     30
1997-01-01     26
1995-01-01     18
1996-01-01     15
1994-01-01     14
1991-01-01     14
1993-01-01     12
2024-01-01     11
1992-01-01      9
1990-01-01      6
1985-01-01      5
1989-01-01      4
1988-01-01      4
1980-01-01      3
1983-01-01      2
1981-01-01      2
1982-01-01      1
1986-01-01      1
1984-01-01      1
1979-01-01      1
1975-01-01      1
1987-01-01      1
Name: count, dtype: int64

Duration
1.0     409
4.0     386
7.0     382
5.0     360
3.0     332
2.0     327
6.0     326
9.0     322
8.0     317
10.0    270
11.0    261
12.0    249
13.0    240
14.0    215
15.0    163
17.0    138
16.0    136
19.0    112
18.0    111
20.0     90
23.0     58
22.0     49
24.0     43
25.0     40
21.0     38
26.0     32
27.0     20
29.0     20
28.0     19
31.0     11
33.0     11
30.0      9
32.0      7
35.0      6
38.0      4
34.0      4
40.0      3
44.0      3
36.0      2
42.0      1
41.0      1
39.0      1
43.0      1
0.0       1
48.0      1
Name: count, dtype: int64

UC (E1-E3)
0         2715
E3        1182
E2        1122
E1         511
E4           4
E1+E3        4
E1+ E2       1
E1,E2        1
Name: count, dtype: int64

CD(L1-L4)
0         2950
L3        1211
L1         774
L2         287
L3+L4      153
L1+L4       97
L2+L4       45
L4          14
L3+4         2
L3+L1        2
L1+ L3       1
L1+4         1
L2+4         1
L1           1
L1+L3        1
Name: count, dtype: int64

CD (B1-B3)
0           2948
B1          1298
B2           631
B3           590
B2+B3         44
B1+B2         13
B1+B3          9
B1             1
B3+B2          1
L3             1
B10            1
B2+ B3         1
B1,B2          1
B1+B2+B3       1
Name: count, dtype: int64

CD (Perianal)
0    4829
1     711
Name: count, dtype: int64

IBD-U
0    5449
1      91
Name: count, dtype: int64

Previous surgery
0            4522
O             333
ICR           278
SBR           157
TAC            61
CL             51
PC             43
IPAA           15
SBR+CL         13
ICR+O          11
ICR+CL          9
CL+SBR          5
SBR+ICR         4
ICR+SBR         3
PC+SBR          3
SBR + O         2
CL+PC           2
IC              2
cl              2
SBR+PC          2
SBR+O           2
C+SBR           1
IPAA+O          1
SRB             1
PC + IPAA       1
PC+IPAA         1
HCR             1
IC              1
CL+IPAA         1
ICR + SBR       1
CL+SBR+O        1
CL+ICR+PC       1
ICR             1
SBR+ICR+O       1
CR+O            1
CL+TAC          1
PC+IPAA         1
CL+O            1
ICR+APR         1
CL+ICR          1
PC              1
Name: count, dtype: int64

5-ASA
0.0    3291
1.0    2249
Name: count, dtype: int64

Azathioprine or 6-MP
0.0    3334
1.0    2206
Name: count, dtype: int64

Methotrexate
0.0    5497
1.0      43
Name: count, dtype: int64

Cyclosporine
0.0    5539
1.0       1
Name: count, dtype: int64

Infliximab
0.0    4746
1.0     794
Name: count, dtype: int64

Certolizumab
0.0    5530
1.0      10
Name: count, dtype: int64

Golimumab
0.0    5492
1.0      48
Name: count, dtype: int64

Adalimumab
0.0    4743
1.0     797
Name: count, dtype: int64

vedolizumab
0.0    5316
1.0     224
Name: count, dtype: int64

current steroid use
0.0    4828
1.0     712
Name: count, dtype: int64

Tofacitinib
0.0    5495
1.0      45
Name: count, dtype: int64

Ustekinumab
0.0    5162
1.0     378
Name: count, dtype: int64

No.of previous biologic used
0                         3580
1                         1391
2                          402
3                          119
4                           30
1 ADA                        4
1 IFX                        4
5                            3
1 INFX                       3
ADA                          1
2 IFX and tofacitinib        1
2 ADA and IFX                1
2 Tofa and ADA               1
Name: count, dtype: int64

EIM
Yes    1480
Name: count, dtype: int64

Other autoimmune diseases
0      5440
R        44
O        26
S        24
R+S       2
H         2
L         1
C         1
Name: count, dtype: int64

Co-morbidities
0          5030
C           101
O            80
D            78
C+D          37
P            34
N            31
R            18
L            16
T            15
C+R           9
C+P           7
D+C           7
C+N           6
C+D+O         5
c             5
C+L           4
C+D+R         4
C+P+D         4
C+D+N         4
C             3
C+N+D         3
C+O           3
D+P           3
R+O           2
DC            2
C+P+N         2
C+P+R+D       2
C+P+N+D       2
P+N+D         1
N+D           1
P+R           1
P+N           1
P+L+R         1
D+ C          1
P             1
D+O           1
D+H           1
H             1
D + P         1
P+O           1
L+D           1
R + O         1
P+N+L         1
L+O           1
C+L+D         1
D+N           1
P+C           1
D+T           1
C+D+T         1
M             1
D+L           1
Name: count, dtype: int64

In [122]:
# Filling missing values with '0' and converting to string
df['Sex'] = df['Sex'].fillna('0').astype(str)
df['Current Smoker'] = df['Current Smoker'].fillna('0').astype(str)
df['Previous surgery'] = df['Previous surgery'].fillna('0').astype(str)
df['No.of previous biologic used'] = df['No.of previous biologic used'].fillna('0').astype(str)
df['EIM'] = df['EIM'].fillna('0').astype(str)
df['Other autoimmune diseases'] = df['Other autoimmune diseases'].fillna('0').astype(str)
df['Co-morbidities'] = df['Co-morbidities'].fillna('0').astype(str)

# Mapping categorical values to numerical values
df['Sex'] = df['Sex'].map({'M': 1, 'F': 0}).fillna(0)  # Mapping 'M' to 1, 'F' to 0
df['Current Smoker'] = df['Current Smoker'].apply(lambda x: 0 if x == '0' else 1)
df['New Previous surgery'] = df['Previous surgery'].apply(lambda x: 0 if x == '0' else 1)
df['New previous biologic used'] = df['No.of previous biologic used'].apply(lambda x: 0 if x == '0' else 1)
df['EIM'] = df['EIM'].apply(lambda x: 0 if x == '0' else 1)
df['New Co-morbidities'] = df['Co-morbidities'].apply(lambda x: 0 if x == '0' else 1)
df['New OAD'] = df['Other autoimmune diseases'].apply(lambda x: 0 if x == '0' else 1)


print(df[['Sex', 'Current Smoker', 'Previous surgery', 'No.of previous biologic used', 'EIM', 'Other autoimmune diseases', 'Co-morbidities']].head())

    Sex  Current Smoker Previous surgery No.of previous biologic used  EIM  \
id
1   1.0               0                0                            2    1
2   0.0               0              ICR                            0    0
3   0.0               0                0                            0    0
4   0.0               0              TAC                            4    0
5   1.0               0                0                            2    0

   Other autoimmune diseases Co-morbidities
id
1                          0              P
2                          0              0
3                          0              0
4                          0              0
5                          0              0

In [123]:
# df['Sex'] = df['Sex'].map({'M': 1, 'F': 0}).fillna(0)
# df['Current Smoker'] = df['Current Smoker'].apply(lambda x: 0 if x == '0' else 1)
# df['New Previous surgery'] = df['Previous surgery'].apply(lambda x: 0 if x == '0' else 1)
# df['New previous biologic used'] = df['No.of previous biologic used'].apply(lambda x: 0 if x == '0' else 1)
# df['EIM'] = df['EIM'].apply(lambda x: 0 if x == '0' else 1)
# df['New Co-morbidities'] = df['Co-morbidities'].apply(lambda x: 0 if x == '0' else 1)
# df['New OAD'] = df['Other autoimmune diseases'].apply(lambda x: 0 if x == '0' else 1)

In [124]:
# cat = df[['Sex', 'New Previous surgery', 'New previous biologic used', 
#        'EIM', 'New OAD', 'New Co-morbidities']]

# for col in cat:
#     print(cat[col].value_counts())
#     print()

In [125]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5540 entries, 1 to 5540
Data columns (total 32 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Country                       5540 non-null   object
 1   Age                           4928 non-null   float64
 2   Sex                           5540 non-null   float64
 3   Current Smoker                5540 non-null   int64
 4   Year of Dx                    5540 non-null   datetime64[ns]
 5   Duration                      5531 non-null   float64
 6   UC (E1-E3)                    5540 non-null   object
 7   CD(L1-L4)                     5540 non-null   object
 8   CD (B1-B3)                    5540 non-null   object
 9   CD (Perianal)                 5540 non-null   object
 10  IBD-U                         5540 non-null   object
 11  Previous surgery              5540 non-null   object
 12  5-ASA                         5540 non-null   float64
 13  Azathioprine or 6-MP          5540 non-null   float64
 14  Methotrexate                  5540 non-null   float64
 15  Cyclosporine                  5540 non-null   float64
 16  Infliximab                    5540 non-null   float64
 17  Certolizumab                  5540 non-null   float64
 18  Golimumab                     5540 non-null   float64
 19  Adalimumab                    5540 non-null   float64
 20  vedolizumab                   5540 non-null   float64
 21  current steroid use           5540 non-null   float64
 22  Tofacitinib                   5540 non-null   float64
 23  Ustekinumab                   5540 non-null   float64
 24  No.of previous biologic used  5540 non-null   object
 25  EIM                           5540 non-null   int64
 26  Other autoimmune diseases     5540 non-null   object
 27  Co-morbidities                5540 non-null   object
 28  New Previous surgery          5540 non-null   int64
 29  New previous biologic used    5540 non-null   int64
 30  New Co-morbidities            5540 non-null   int64
 31  New OAD                       5540 non-null   int64
dtypes: datetime64[ns](1), float64(15), int64(6), object(10)
memory usage: 1.4+ MB

In [126]:
cols_drop = df[['Previous surgery', 'No.of previous biologic used', 'Other autoimmune diseases', 'Co-morbidities']]

df.drop(cols_drop, axis=1, inplace=True)

In [127]:
for col in df:
    print(df[col].value_counts())
    print()

Country
United Kingdom    1802
France            1338
Spain             1017
Italy              768
Poland             377
Greece             238
Name: count, dtype: int64

Age
27.0    171
32.0    169
33.0    167
28.0    158
37.0    154
       ...
87.0      2
83.0      2
91.0      1
82.0      1
84.0      1
Name: count, Length: 81, dtype: int64

Sex
1.0    2874
0.0    2666
Name: count, dtype: int64

Current Smoker
0    4972
1     568
Name: count, dtype: int64

Year of Dx
2019-01-01    445
2018-01-01    442
2017-01-01    375
2020-01-01    353
2015-01-01    347
2016-01-01    326
2021-01-01    308
2014-01-01    278
2022-01-01    277
2013-01-01    272
2012-01-01    263
2011-01-01    240
2010-01-01    232
2023-01-01    171
2008-01-01    168
2009-01-01    167
2007-01-01    136
2006-01-01    113
2005-01-01    105
2004-01-01     89
2003-01-01     64
2000-01-01     62
2002-01-01     47
2001-01-01     42
1998-01-01     37
1999-01-01     30
1997-01-01     26
1995-01-01     18
1996-01-01     15
1994-01-01     14
1991-01-01     14
1993-01-01     12
2024-01-01     11
1992-01-01      9
1990-01-01      6
1985-01-01      5
1989-01-01      4
1988-01-01      4
1980-01-01      3
1983-01-01      2
1981-01-01      2
1982-01-01      1
1986-01-01      1
1984-01-01      1
1979-01-01      1
1975-01-01      1
1987-01-01      1
Name: count, dtype: int64

Duration
1.0     409
4.0     386
7.0     382
5.0     360
3.0     332
2.0     327
6.0     326
9.0     322
8.0     317
10.0    270
11.0    261
12.0    249
13.0    240
14.0    215
15.0    163
17.0    138
16.0    136
19.0    112
18.0    111
20.0     90
23.0     58
22.0     49
24.0     43
25.0     40
21.0     38
26.0     32
27.0     20
29.0     20
28.0     19
31.0     11
33.0     11
30.0      9
32.0      7
35.0      6
38.0      4
34.0      4
40.0      3
44.0      3
36.0      2
42.0      1
41.0      1
39.0      1
43.0      1
0.0       1
48.0      1
Name: count, dtype: int64

UC (E1-E3)
0         2715
E3        1182
E2        1122
E1         511
E4           4
E1+E3        4
E1+ E2       1
E1,E2        1
Name: count, dtype: int64

CD(L1-L4)
0         2950
L3        1211
L1         774
L2         287
L3+L4      153
L1+L4       97
L2+L4       45
L4          14
L3+4         2
L3+L1        2
L1+ L3       1
L1+4         1
L2+4         1
L1           1
L1+L3        1
Name: count, dtype: int64

CD (B1-B3)
0           2948
B1          1298
B2           631
B3           590
B2+B3         44
B1+B2         13
B1+B3          9
B1             1
B3+B2          1
L3             1
B10            1
B2+ B3         1
B1,B2          1
B1+B2+B3       1
Name: count, dtype: int64

CD (Perianal)
0    4829
1     711
Name: count, dtype: int64

IBD-U
0    5449
1      91
Name: count, dtype: int64

5-ASA
0.0    3291
1.0    2249
Name: count, dtype: int64

Azathioprine or 6-MP
0.0    3334
1.0    2206
Name: count, dtype: int64

Methotrexate
0.0    5497
1.0      43
Name: count, dtype: int64

Cyclosporine
0.0    5539
1.0       1
Name: count, dtype: int64

Infliximab
0.0    4746
1.0     794
Name: count, dtype: int64

Certolizumab
0.0    5530
1.0      10
Name: count, dtype: int64

Golimumab
0.0    5492
1.0      48
Name: count, dtype: int64

Adalimumab
0.0    4743
1.0     797
Name: count, dtype: int64

vedolizumab
0.0    5316
1.0     224
Name: count, dtype: int64

current steroid use
0.0    4828
1.0     712
Name: count, dtype: int64

Tofacitinib
0.0    5495
1.0      45
Name: count, dtype: int64

Ustekinumab
0.0    5162
1.0     378
Name: count, dtype: int64

EIM
0    4060
1    1480
Name: count, dtype: int64

New Previous surgery
0    4522
1    1018
Name: count, dtype: int64

New previous biologic used
0    3580
1    1960
Name: count, dtype: int64

New Co-morbidities
0    5030
1     510
Name: count, dtype: int64

New OAD
0    5440
1     100
Name: count, dtype: int64

In [128]:
df['Age ']= df['Age '].fillna(df['Age '].median())
df['Duration']= df['Duration'].fillna(df['Duration'].median())

In [129]:
df.isnull().sum()

Country                       0
Age                           0
Sex                           0
Current Smoker                0
Year of Dx                    0
Duration                      0
UC (E1-E3)                    0
CD(L1-L4)                     0
CD (B1-B3)                    0
CD (Perianal)                 0
IBD-U                         0
5-ASA                         0
Azathioprine or 6-MP          0
Methotrexate                  0
Cyclosporine                  0
Infliximab                    0
Certolizumab                  0
Golimumab                     0
Adalimumab                    0
vedolizumab                   0
current steroid use           0
Tofacitinib                   0
Ustekinumab                   0
EIM                           0
New Previous surgery          0
New previous biologic used    0
New Co-morbidities            0
New OAD                       0
dtype: int64

After inputing numeric variable with their medians and remaining categoricl  (Yes/No) variables into 1,0 for statistical analysis, there are no more missing data as seen above.

#### TARGET Variable

In [133]:
df['UC'] = df['UC (E1-E3)'].apply(lambda x : x if x == '0' else 1)
df['CD(L1-L4)'] = df['CD(L1-L4)'].apply(lambda x : x if x == '0' else 1)

In [134]:
# Count of Target variable
df['UC'].value_counts()

UC
1    2825
0    2715
Name: count, dtype: int64

In our data we have 2825 patients with Ulcerative Colitis condition.

In [132]:
cleaned_data = df.to_csv('cleaned_data.csv', index=False)